version: '3.8'
services:
  postgres:
    image: postgres:16.1
    environment:
      - POSTGRES_USER=jeanmichel
      - POSTGRES_PASSWORD=keycloak
      - POSTGRES_DB=toto
    ports:
      - "5432:5432"
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.0
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_USERNAME=jeanmichel
      - KC_DB_PASSWORD=keycloak
      - KC_DB_URL=jdbc:postgresql://postgres:5432/toto
    depends_on:
      - postgres
    command: start-dev

